package sbnz.integracija;


import java.util.*;
import com.example.MusicRecc.model.Korisnik;
import com.example.MusicRecc.model.*;
import com.example.MusicRecc.model.Pesma;

//
//query songIsContainedIn(Pesma p)
//    Korisnik(omiljenePesme: omiljenePesme.contains(p))
//end
rule "Find korisnik favorite songs from ocene"
    agenda-group "korisnik_rules"
    lock-on-active true
    when
        $korisnik : Korisnik($ocene : istorijaOcena)
        $favoriteSongs: Set() from accumulate
        (
            Ocena($ocena: this) from $ocene,
            init
            (
                Set<Pesma> setPesama = new HashSet<Pesma>();
            ),
            action
            (
                if($ocena.getOcena() > 3){
                    setPesama.add($ocena.getPesma());
                }
            ),
            result
            (
                new HashSet<>(setPesama)
            )
        )
    then
        modify($korisnik){setOmiljenePesme($favoriteSongs)}
        System.out.println("Check song points " +  $favoriteSongs);
    end

