
package sbnz.integracija;

import com.example.MusicRecc.model.Ocena;
import com.example.MusicRecc.model.Pesma;
import com.example.MusicRecc.model.Korisnik;
import com.example.MusicRecc.model.*;
import java.time.LocalDateTime;
import java.math.BigInteger;

global Integer songsRankCounter;


rule "Check song points"
    salience 30
    agenda-group "song_score"
    lock-on-active true
    when
        $p : Pesma(points == null || points != 10)
    then
        modify($p){setPoints(10)};
        System.out.println("Check song points " +  $p.getPoints());
end
rule "Calculate song average"
	salience 19
	agenda-group "song_score"
	lock-on-active true
    when
        $p : Pesma($ocene : ocene != null)
        $value: Number(floatValue >= 0) from accumulate
        (
			Ocena($ocena: this) from $ocene,
			init
			(
				float count = 0;
			),
			action
			(
				count += $ocena.getOcena();
			),
			result
			(
				count/($ocene.size())
		    )
        )
    then
    	float count = $value.floatValue();
        System.out.println("AverageRating " + count);
        modify($p){setAverageOcena(count)};
    end
rule "Calculate song streams in date range"
	salience 19
	agenda-group "song_score"
	lock-on-active true
    when
        $p : Pesma($slusanja: slusanja)
        $dateAfter: LocalDateTime()
        $value: Number(intValue >= 0) from accumulate
        (
			Slusanje($slusanje: this) from $slusanja,
			init
			(
				int count = 0;
			),
			action
			(
                if($slusanje.getDatumSlusanja().isAfter($dateAfter)){
                    count += 1;
                }

			),
			result
			(
				count
		    )
        )
    then
    	int count = $value.intValue();
        System.out.println("Number of streams " + count);
        modify($p){setBrojSlusanja( BigInteger.valueOf(count))};
    end
rule "Short song"
    salience 5
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(duzina < 120)
    then

        modify($p){setPoints($p.getPoints() - 0.7)};
        System.out.println("SHORT SONG " +  $p.getPoints());
end
rule "Medium lenght song"
    salience 5
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(duzina >= 120,duzina <= 300)
    then
        modify($p){setPoints($p.getPoints() + 0.9)};
        System.out.println("MEDIUM SONG " +  $p.getPoints());

end
rule "Long song"
    salience 5
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(duzina > 300)
    then
        modify($p){setPoints($p.getPoints() + 0.5)};
        System.out.println("LONG SONG" +  $p.getPoints());

end
//

rule "Below average score"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(averageOcena < 2.5)
    then
        modify($p){setPoints($p.getPoints() * 0.8)};
        System.out.println("Below average rating" + $p.getPoints());
    end
rule "Average score"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(averageOcena >= 2.5, averageOcena <4)
    then
        modify($p){setPoints($p.getPoints() *1.2)};
        System.out.println("Average score rule points " + $p.getPoints());
    end
rule "Above average score"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(averageOcena >= 4)
    then
        modify($p){setPoints($p.getPoints()*1.5)};
        System.out.println("Above average " + $p.getPoints());
    end

rule "Below 10.000 listenings"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(brojSlusanja < 10000)
    then
        modify($p){setPoints($p.getPoints()+3)};
        System.out.println("Below 10.000 listenings " + $p.getPoints());
    end
rule "Between 10.000 - 100.000 listenings"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(brojSlusanja >= 10000,brojSlusanja < 100000)
    then
        modify($p){setPoints($p.getPoints()+3)};
        System.out.println("Between 10.000 - 100.000 listenings " + $p.getPoints());
    end

rule "Between 100.000 - 1000.000 listenings"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(brojSlusanja >= 100000,brojSlusanja < 1000000)
    then
        modify($p){setPoints($p.getPoints()+4)};
        System.out.println("Between 100.000 - 1000.000 listenings " + $p.getPoints());
    end

rule "More then 1.000.000 listenings"
    salience 10
    agenda-group "song_score"
    no-loop
    when
        $p : Pesma(brojSlusanja >= 1000000)
    then
        modify($p){setPoints($p.getPoints()+5)};
        System.out.println("More than milion listening" + $p.getPoints());
    end


rule "The most popular songs"
	agenda-group "popularity"
	salience (100*($p.getPoints()+1))
	when
		$p:  Pesma();
		eval(songsRankCounter != null && songsRankCounter < 3)
	then
	    drools.getKnowledgeRuntime().setGlobal("songsRankCounter", songsRankCounter + 1);
	    if(songsRankCounter < 3){
            System.out.println("\tHighest ranked song => : " + $p.getNaziv() + " " + $p.getPoints());
	    }
end;